config/routes.rb
Rails.application.routes.draw do
  root to: "videos#index"

  resources :videos, only: %w(show index)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @tag = query.fetch(:tags, 'all')
    @refresh_params = refresh_params
    @videos, @errors = Zype::Video.list(query, clear_cache)
  end

  def show
    @video = Zype::Video.find(params[:id])
  end

  private
  def query
    params.fetch(:query, {})
  end

  def clear_cache
    params[:clear_cache].present?
  end

  def refresh_params
    refresh = { clear_cache: true }
    refresh.merge!({ query: query }) if query.present?
    refresh
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="es">
  <head>
    <title>Zype app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content=""> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
 
  </head>
 
  <body>
     <%= render "layouts/shared/topbar" %>
     <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="main-grids">
        <%= yield %>
      </div>
     </div>
     <%= render "layouts/shared/sidebar" %>
  </body>
</html>

app/views/layouts/shared/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <div class="top-navigation">
    <div class="t-menu">MENU</div>
    <div class="t-img">
      <img src="/assets/lines.png" alt="" />
    </div>
    <div class="clearfix"> </div>
  </div>
  <div class="drop-navigation drop-navigation">
    <ul class="nav nav-sidebar">
      <li class="active"><a href="index.html" class="home-icon"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
    <div class="side-bottom">
      <div class="copyright">
        <p>Copyright © 2019 Zype. All Rights Reserved</a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <h1><img src="/assets/logo.png" alt="" /></h1>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    </div>
    <div class="clearfix"> </div>
  </div>
</nav>

app/views/videos/index.html.erb
<% if @errors %>
  <%= @errors[:message] %>
<% else %>
  <div class="recommended">
    <div class="recommended-grids">
      <div class="recommended-info">
        <h1>Recommended videos</h1>
      </div>
      <% @videos.each do |video| %>
        <div class="col-md-3 resent-grid recommended-grid">
          <div class="resent-grid-img recommended-grid-img">
            <a href="<%= video_path(video._id) %>"><img src="<%= video.image_url %>" alt="" /></a>
          </div>
          <div class="resent-grid-info recommended-grid-info video-info-grid">
            <h5><a href="single.html" class="title"><%= video.title %></a></h5>
            <div class="time-container">
              <div class="clck small-clck">
                <span class="glyphicon glyphicon-time clck-icon" aria-hidden="true"></span>
                <p class="clck-time"><%= Time.at(video.duration).utc.strftime("%H:%M:%S") %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/videos/show.html.erb
<% if @video.errors %>
  <%= @video.errors[:message] %>
<% else %>
<div class="show-top-grids">
  <div class="col-sm-8 single-left">
    <div class="song">
      <div class="song-info">
        <h3><%= @video.title %></h3>	
    </div>
      <div class="video-grid">
        <div id="<%= @video.zype_id %>"></div>
          <script src="<%= @video.zype_script %>" type="text/javascript"></script>
        </div>
      </div>
    </div>
    	<div class="song-grid-right">
        <div class="share">
          <h5>Share this</h5>
          <ul>
            <li><a href="#" class="icon fb-icon">Facebook</a></li>
            <li><a href="#" class="icon dribbble-icon">Dribbble</a></li>
            <li><a href="#" class="icon twitter-icon">Twitter</a></li>
            <li><a href="#" class="icon pinterest-icon">Pinterest</a></li>
            <li><a href="#" class="icon whatsapp-icon">Whatsapp</a></li>
            <li><a href="#" class="icon like">Like</a></li>
            <li><a href="#" class="icon comment-icon">Comments</a></li>
          </ul>
        </div>
      </div>
    <div class="clearfix"> </div>
    <div class="published col-sm-8">
      <div class="load_more">	
      <h4>Published at <%= @video.published_at.to_time.utc.to_formatted_s(:long_ordinal) %></h4>
      <p><%= @video.description %></p>
      </div>
    </div>
  </div>
</div>
<% end %>